### ISSUE TITLE
|FRONT-END| Crie uma página para visualizar a relação de funcionários #13

### ISSUE THREAD

**Issue by Mossatto** [Mossatto/helpr-front-jfs5#1]
A relação de funcionários deve ser criada em forma de tabela. A tabela deve inicializar os dados, automaticamente. Crie também o modelo de Funcionario para agrupar os dados. O modelo deve respeitar o formato que foi definido pela API. Utilize o mecanismo de carregamento lento (Lazy Loading). Crie também um novo item na lista de navegação da navbar, para referenciar a relação de funcionários (utilize o ícone support_agent). A página deve preservar a identidade visual estabelecida, como mostrar em anexo na relação de clientes.

**Comment by danielmurilo** [comment]
criado módulo de funcionarios
